### ISSUE TITLE
Allow customizing disk space for GKE deployment

### ISSUE THREAD

**Issue by melissachang** [DataBiosphere/data-explorer-indexers#120]
- Nov 29 - Indexer for biobank-explorer.appspot.com ran
- Some time before Dec 23, es-data-2 logs started having ["No space left on device"](https://gist.githubusercontent.com/melissachang/5642f01c986c708a8d6ce24c72cb68cb/raw/a87c55f3019e4522096bfba395908474bbfc3b7c/gistfile1.txt). Elasticsearch cluster health (_cluster/health) became red.

In deploy.json, there should be a way to specify more disk space.

**Comment by bfcrampton** [comment]
FYI scaling the # of data nodes effectively increases the total disk space available on the deployment. Currently each data node is provisioned a 12GB disk for storage: https://github.com/DataBiosphere/data-explorer-indexers/blob/master/kubernetes-elasticsearch-cluster/es-data-stateful.yaml#L80. 

How big is the biobank dataset?

**Comment by melissachang** [comment]
Thanks. I think I was using a verison of #114 which accidentally changed es-data storage from 12Gi to 2Gi. So never mind on this issue.
