### ISSUE TITLE
Reindex with zero downtime

### ISSUE THREAD

**Issue by melissachang** [DataBiosphere/data-explorer-indexers#121]
It can take several hours to index a larger dataset (NHS, UKBB). Currently, the DE UI is down during reindexing. We should make it so that DE UI remains usable during indexing.

I see two main approaches:

**Approach 1 - Use [ES Index Alias](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html)**

This seems to be what most people do.

Note: This approach can be tested on local machine. Though as part of testing the PR, it should be tested on GKE -- both DE UI and raw multi_match query.

The GKE cluster would have to have enough capacity to support both indexing and querying at the same time. From the latest indexing of NHS on GKE:

- Cluster had total of 260G memory and 40 cpu
- ES data nodes used ~34.5G (out of 160G allocated), ~11.5 cpu, 167M disk
- Indexer used .3 cpu, 3.9G, 370M disk

With this configuration, it appears querying would still work. Though this might mean our cluster is overprovisioned (for most of the time when we're not reindexing), and we're paying too much.

**Approach 2 - Create second GKE cluster**

Unlike Approach 1, GAE api server would also need to be redeployed (to update ELASTICSEARCH_URL). 

Advantages of this approach:
- Don't have to worry about indexer making DE UI slower
- Don't need to complicate indexer code. Can be implemented as shell script (deploy-indexer-in-second-cluster.sh).
- Projects that don't need extra complexity can skip this. They would just run deploy-indexer.sh instead of 
deploy-indexer-in-second-cluster.sh

Flow
- deploy-indexer-in-second-cluster.sh:
  - Create second cluster named `elasticsearch-cluster-<timestamp>`. We could use [labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/), eg "environment": "prod"/"staging".
  Or `elasticsearch-cluster-<monotonically-increasing-number>`
  - Deploy ES, deploy indexer
    - deploy-indexer.sh needs a for loop at the end to poll when indexer.py is done. (kubectl 1.11 introduces `kubectl wait`, but the kubectl that is shipped with gcloud is still 1.10.)
  - Figure out ELASTICSEARCH_URL and redeploy api server
    Could use labels. Or highest number/timestamp.
- User manually verify if UI looks good
- User deletes original cluster

---

Let's try Approach 2 and see how it works.

**Comment by melissachang** [comment]
Actually now I'm leaning towards Approach 2. I'll write more on Monday.

**Comment by wnojopra** [comment]
lets fix #127 before this

**Comment by wnojopra** [comment]
I've started work on this now - a few things I've found we need to look out for:

Creating a cluster requires 7 additional instances, and I think most projects have a relatively low quota for this. I needed to request more quota on my personal project to allow for this. I took a look at the other data explorers (both baselines, amp-pd, nhs), and they are good for quota for now. 

Given the above point - it'll be pretty important to delete the original cluster. 

Looks like in February, 1.11 became the default for new clusters, and 1.10.x is no longer available. This should mean we can safely use kubectl wait.

**Comment by wnojopra** [comment]
Also to consider for quota is each new cluster requires 12 CPUs in Compute Engine API. I needed to request more for my personal project. Looking real quickly, I see for amp-pd-data-explorer we will need to request more.

**Comment by melissachang** [comment]
SG, requesting quota increases should be documented somewhere. After [Run Indexer on GKE](https://github.com/DataBiosphere/data-explorer-indexers/tree/master/bigquery/deploy#run-indexer-on-gke), there could be a "Reindex with no downtime" section.

**Comment by wnojopra** [comment]
So as discussed, instead of writing a deploy-indexer-in-second-cluster.sh, we just modify the scripts to:

1) create-cluster creates a cluster name with a timestamp suffix
2) deploy-es, deploy-indexer, deploy-api will sort the list of clusters, and choose to use the one with the greatest timestamp (most recent)
3) The user will need to clean up the old clusters.

The readmes will be updated to give a short list of commands to run to complete this.

**Comment by wnojopra** [comment]
Fixed via #134
