### ISSUE TITLE
BQ indexer fails when "participant_id_column" points to a repeated field

### ISSUE THREAD

**Issue by danxmoran** [DataBiosphere/data-explorer-indexers#73]
In the ENCODE dataset, files can contain data from multiple donors. This one-to-many relationship can be represented in BQ using a repeated column, but when I try to index the tables (mapping files -> samples and donors -> participants), I get the following error:
```
2018092714:01:20    base.py:83 INFO HEAD http://10.128.0.5:9200/encode [status:200 request:0.009s]
2018092714:01:20 indexer_util.py:99 INFO Using existing encode index at http://10.128.0.5:9200/.
2018092714:01:20 indexer.py:97 INFO Adding nested sample mapping to encode.
2018092714:01:20    base.py:83 INFO PUT http://10.128.0.5:9200/encode/_mapping/type [status:200 request:0.082s]
2018092714:01:20 indexer.py:192 INFO Indexing broad-gdr-encode-storage.encode_09_26_2018.files into encode.
2018092714:01:45 indexer.py:199 INFO BigQuery -> pandas took 00h:00m:25s
2018092714:01:45 indexer.py:200 INFO broad-gdr-encode-storage.encode_09_26_2018.files has 48448 rows
2018092714:01:45    base.py:97 WARNING POST http://10.128.0.5:9200/_bulk [status:400 request:0.007s]
Traceback (most recent call last):
  File "/app/indexer.py", line 261, in <module>
Index name: encode
Elasticsearch took 0 seconds to come up.
    main()
  File "/app/indexer.py", line 256, in main
    sample_id_column, sample_file_columns)
  File "/app/indexer.py", line 215, in index_table
    indexer_util.bulk_index_scripts(es, index_name, scripts_by_id)
  File "/usr/local/lib/python2.7/site-packages/indexer_util/indexer_util.py", line 126, in bulk_index_scripts
    bulk(es, es_actions(scripts_by_id), request_timeout=60)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 257, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 192, in streaming_bulk
    raise_on_error, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 99, in _process_bulk_chunk
    raise e
elasticsearch.exceptions.RequestError: TransportError(400, u'illegal_argument_exception', u'Malformed action/metadata line [1], expected a simple value for field [_id] but found [START_ARRAY]')
```
I've confirmed that the error goes away if I filter out records for files from multiple donors and remove the array wrappers.

gcloud's IAM won't let me grant reader access to `allUsers` on the BQ dataset causing the error, but if there's a specific Google group I could share it with for debugging I'd be happy to do so! I've also dropped the JSON used to build the tables in the set into a public GCS bucket at `gs://broad-gdr-encode-ingest-staging/09-26-2018/`. I'm using:
```
{
  "participant_id_column": "donor_accession",
  "sample_id_column": "file_accession"
}
```

**Comment by bfcrampton** [comment]
Would it be possible for the data to be transformed in such a way that the `participant_id_column` is not repeated? i.e. instead of something like:
```
participant_ids,file_path
1,2,3,gs://some-path
```
make it:
```
participant_id|file_path
1|gs://some-path
2|gs://some-path
3|gs://some-path
```

**Comment by melissachang** [comment]
I agree with Bryan, I don't want to support repeated primary key out of the box, because I think it will be unusual.

For example, for 1000 Genomes all participants have the same VCF file. The VCF column is the the same for everyone:
```
SELECT * FROM `verily-public-data.human_genome_variants.1000_genomes_sample_info`
WHERE NOT chr_1_vcf IS NULL
```

The easiest way to make a dataset public is using the BigQuery web UI. I don't see a way in the new BigQuery web UI, but from the [old BigQuery web UI](https://bigquery.cloud.google.com): Click on dataset triangle drop-down -> Share dataset -> All Authenticated Users. Or you can share with melchang@google.com and bryancrampton@google.com. Thanks.

**Comment by danxmoran** [comment]
Just to clarify, the repeated column isn't a primary key in the files/samples table, it's a foreign key back into the donors/participants table. This sort of relationship is pretty common in the data we work with, and especially common for epigenomic data (we're already stretching to flatten the [original schema](https://www.encodeproject.org/profiles/graph.svg) into a samples/participants model). Attaching files at the participant level would come with a similar problem because each donor's info is present in multiple files, so we'd end up with a column of repeated structs which would need to be indexed.

I've added you both as BQ data viewers on the project [`broad-gdr-encode-storage`](https://console.cloud.google.com/bigquery?project=broad-gdr-encode-storage&organizationId=548622027621&p=broad-gdr-encode-storage&d=encode_09_26_2018&page=dataset). Let me know if you aren't able to access something you need!

**Comment by danxmoran** [comment]
My concern isn't storage cost, it's that duplicating the file rows would require munging their primary keys in a way that loses information.

For example, if I want to split a multi-donor row:

file_accession|donor_accession
--------------|-----------------
fileA|[donorA, donorB, donorC]

The 2 options I see are to either reuse the `file_accession` value for each row (in which case it's not really a PK in the table any more):

file_accession|donor_accession
--------------|-----------------
fileA|donorA
fileA|donorB
fileA|donorC

Or to make up new IDs for each row, which would prevent key clashes but make it more difficult for end users to link data from other sources:

file_accession|donor_accession
--------------|-----------------
fileA_A|donorA
fileA_B|donorB
fileA_C|donorC

The BQ table was generated from the JSON at `gs://broad-gdr-encode-ingest-staging/09-26-2018/files.bq.json`. That JSON was generated by munging & merging raw metadata pulled from ENCODE's API, so it'd be difficult to reconstruct the sample<->donor links from it. I didn't keep the intermediate downloads around, but I can re-download the info for today (and re-generate corresponding BQ JSON) and upload it all to `gs://broad-gdr-encode-ingest-staging/10-02-2018/`. I'll ping here again when it's ready.

My immediate concern is that using biosample as the primary entity in the 2nd table would just trade one many-to-many relationship for another, since samples could generate multiple files and files could contain data from multiple samples:

biosample_accession|file
---------------------|---
sampleA|[{ "id": "A", "type": "bam" },{ "id": "B", "type": "bigWig" },{ "id": "C", "type": "bam" } ]
sampleB|[{ "id": "B", "type": "bigWig"},{ "id": "D", "type": "bam" }]

Maybe it won't be as big of an issue since it'll be pushed out of the two columns the indexer treats specially.

**Comment by danxmoran** [comment]
`gs://broad-gdr-encode-ingest-staging/10-02-2018/` now contains both raw metadata from ENCODE and the final metadata which would be fed into BQ. `biosamples.json` contains the info for linking sample->donor (each object should have a `donor` field).

**Comment by melissachang** [comment]
For any table with sample primary key, what must be unique is `[sample primary key *and* participant primary key]`.

For example, this table:

file_accession|donor_accession|lab_name
--------------|-----------------|-----------------
fileA|donorA|labA
fileA|donorB|labB
fileA|donorC|labC

Looks like this in Elasticsearch (described [here](https://github.com/DataBiosphere/data-explorer-indexers#main-dataset-index) and [here](https://github.com/DataBiosphere/data-explorer-indexers/tree/master/bigquery#overview)):
```
  "hits" : {
    "total" : 3,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "encode_test",
        "_type" : "type",
        "_id" : "donorA",
        "_score" : 1.0,
        "_source" : {
          "samples" : [
            {
              "file_accession" : "fileA",
              "melchang-test-project-3.encode.test.lab_name" : "labA"
            }
          ]
        }
      },
      {
        "_index" : "encode_test",
        "_type" : "type",
        "_id" : "donorC",
        "_score" : 1.0,
        "_source" : {
          "samples" : [
            {
              "file_accession" : "fileA",
              "melchang-test-project-3.encode.test.lab_name" : "labC"
            }
          ]
        }
      },
      {
        "_index" : "encode_test",
        "_type" : "type",
        "_id" : "donorB",
        "_score" : 1.0,
        "_source" : {
          "samples" : [
            {
              "file_accession" : "fileA",
              "melchang-test-project-3.encode.test.lab_name" : "labB"
            }
          ]
        }
      }
    ]
  }
```

And the facet looks like:
![encode](https://user-images.githubusercontent.com/10929390/46381011-5e394280-c659-11e8-8e0b-e20563f99f47.png)

If you had duplicate `[sample primary key, participant primary key]`, then you would lose information.

file_accession|donor_accession|lab_name
--------------|-----------------|-----------------
fileA|donorA|labA
fileA|donorA|labB

Does that unblock you?

Btw -- After looking at your BQ table, I no longer thinking sample primary key == `biosample_accession` is necessarily better. Sample primary key makes sense when there's predictable file types. For example, for [1000 Genomes](http://www.internationalgenome.org/), samples might have "WGS High Coverage BAM", "WGS Lower Coverage BAM", etc. From your BQ table, there appears to be no rhyme or reason for what files a sample is associated with. So using `file_accession` as the sample primary key SGTM.

**Comment by danxmoran** [comment]
Thanks @melissachang, that did unblock me. I submitted a PR to add it to the docs, then I'm happy for this to be closed out.
