### ISSUE TITLE
Views no longer supported by the BigQuery indexer

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/data-explorer-indexers#99]
Was trying to index a `samples` view, which pulls together a few different BigQuery tables (one has the GCS paths, another has sequencing metrics, another has variant calling metrics), but I got:

```
indexer_1_b82b50929db0 | 2018111501:10:31 indexer.py:197 INFO Running extract table job for:<datset>.wgs_samples
indexer_1_b82b50929db0 | Traceback (most recent call last):
indexer_1_b82b50929db0 |   File "indexer.py", line 412, in <module>
indexer_1_b82b50929db0 |     main()
indexer_1_b82b50929db0 |   File "indexer.py", line 403, in main
indexer_1_b82b50929db0 | Index name: <blah>
indexer_1_b82b50929db0 | Elasticsearch took 0 seconds to come up.
indexer_1_b82b50929db0 |     sample_file_columns, deploy_project_id)
indexer_1_b82b50929db0 |   File "indexer.py", line 205, in index_table
indexer_1_b82b50929db0 |     job.result(timeout=600)
indexer_1_b82b50929db0 |   File "/usr/local/lib/python2.7/site-packages/google/cloud/bigquery/job.py", line 697, in result
indexer_1_b82b50929db0 |     return super(_AsyncJob, self).result(timeout=timeout)
indexer_1_b82b50929db0 |   File "/usr/local/lib/python2.7/site-packages/google/api_core/future/polling.py", line 120, in result
indexer_1_b82b50929db0 |     raise self._exception
indexer_1_b82b50929db0 | google.api_core.exceptions.BadRequest: 400 Using table <dataset>.wgs_samples@1542244232101 is not allowed for this operation because of its type. Try using a different table that is of type TABLE.
```

I suspect this is because the indexer is now looking into the schema to try to get column descriptions (for facet search). Views do support having column descriptions, so I think this should be supported.

**Comment by melissachang** [comment]
FYI @wnojopra 

Here's the [Issue for reading from pandas being slow](https://github.com/pydata/pandas-gbq/issues/133). If this is fixed, we could switch back to BQ -> pandas.

**Comment by wnojopra** [comment]
What we could potentially do:

Check if the table you're trying to index is a view (if table.table_type == 'VIEW')
If it is, create a new table that has the same data of that view. 
We'll need to pull the sql query of that view, and re-execute it. 
This table should be created in the project specified in deploy.json. 
We'll use a dataset named 'dataset_for_view_exports'. If it doesn't exist in that project, create it.
Index this new table instead. Delete the table afterwards. It should be ok to leave the dataset around.

**Comment by mbookman** [comment]
Question on one thing:

- We'll need to pull the sql query of that view, and re-execute it.

Would it be sufficient to just do a "CREATE TABLE *temp* AS SELECT * FROM *view*"?

**Comment by melissachang** [comment]
I agree, I think Matt's approach is simpler

**Comment by wnojopra** [comment]
I think Melissa suggested that to me yesterday, but I misunderstood it as "SELECT * FROM original_table" instead of from the view. I agree your approach is simpler.
